config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :photos
  root "photos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord

 validates_presence_of :title, :date, :description, :file_location

 mount_uploader :file_location, PhotoImageUploader  
  validates_presence_of :title, :date, :description, :file_location   

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all.order("created_at DESC")
  end
  def new
  @photo = Photo.new
  end
  def create
  @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to photos_url
    else
      render  :action => :new
    end
  end
  
  def show
  @photo = Photo.find(params[:id])
  end 
  
  
  def edit
  @photo = Photo.find(params[:id])
  end

  def update
   @photo = Photo.find(params[:id])
    if @photo.update_attributes(photo_params)
      redirect_to photo_path(@photo)
    else
      render  :action => :edit
    end
  end

  def destroy
  @photo = Photo.find(params[:id])
  @photo.destroy

  redirect_to photos_url
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :date, :description, :file_location)
  end
  



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoAlbum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<header>
    <div class="nav">
      <div class="container">
        <div class="row">
          <div id="logo" class="pull-left">
            <%= link_to root_url do %>
            <%= image_tag ('download.png'), class: 'img-responsive' %>
            <% end %>
          </div>
          <div class="ftn pull-right">
            <%= link_to '新增相片', new_photo_path, class: 'add-photo' %>
          </div>

        </div>
        
      </div>

    </div>
  </header>




  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<table class="table table-striped table-condensed">
 <% @photos.each do |photo| %>
   <tr>
     <td><%= photo.title %></td>
     <td><%= link_to 'Show', photo_path(photo) %></td>
     <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
     <td><%= link_to 'Destroy', photo_path(photo), method: :delete, data:{ confirm: "Are you sure?" } %></td>
   </tr>
 <% end %>
</table>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/edit.html.erb
<%= render :partial => "form" %>

app/views/photos/index.html.erb
<table class="table table-striped table-condensed">
 <% @photos.each do |photo| %>
   <tr>
     <td><%= photo.title %></td>
     <td><%= link_to 'Show', photo_path(photo) %></td>
     <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
     <td><%= link_to 'Destroy', photo_path(photo), method: :delete, data:{ confirm: "Are you sure?" } %></td>
   </tr>
 <% end %>
</table>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<%= render :partial => "form" %>

app/views/photos/show.html.erb
<%= @photo.title %>
<%= @photo.date %>
<%= image_tag @photo.file_location.url, size: "140x140", class: "img-thumbnail" %>
<%= simple_format(@photo.description) %>

<p><%= link_to 'Back to index', photos_path %></p>